// <auto-generated />
namespace DWH_Automation_Testing.DanElzer.CostofgoodsSold_Output
{
    using global::System;
    using global::System.Diagnostics.CodeAnalysis;
    using global::System.Resources;
    using global::System.Globalization;
    using global::System.ComponentModel;
    using global::System.CodeDom.Compiler;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [DebuggerNonUserCode]
    [CompilerGenerated]
    internal class Resources
    {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    ResourceManager temp = new ResourceManager("DWH_Automation_Testing.DanElzer.CostofgoodsSold_Output.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;&lt;TestManifest failOnServerPublishFailureExpression=&quot;False&quot; testSuiteId=&quot;d78c7154-04e6-45ca-bda5-110919ee4e18&quot; testSuiteName=&quot;Cost of goods Sold&quot; testGroupId=&quot;b701adc3-f420-4009-8e08-e425a8b80dbc&quot; testGroupName=&quot;Cost of goods Sold&quot; isSingleGroupMode=&quot;True&quot; publishUrl=&quot;https://test-api.sentryone.com&quot; publishUserName=&quot;asingh@barfoot.co.nz&quot; publishorganizationIdentifier=&quot;346&quot; accessToken=&quot;OcjV3EfxP3aWHJten0vq8y1hlAFEIPCqVPq0m7FDq5aQWcKm0kaYv/Nwmewb18la0ik/zkxA5CBIARokLVARr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestManifest_CostofgoodsSold_b701adc3f42040098e08e425a8b80dbc
        {
            get
            {
                return ResourceManager.GetString("TestManifest_CostofgoodsSold_b701adc3f42040098e08e425a8b80dbc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // DAX Query
        ///DEFINE VAR __DS0FilterTable = 
        ///  TREATAS({&quot;2019-2020&quot;}, &apos;Date&apos;[Financial Year (Calendar)])
        ///
        ///EVALUATE
        ///  TOPN(
        ///    501,
        ///    SUMMARIZECOLUMNS(
        ///      &apos;Date&apos;[Financial Year (Calendar)],
        ///      __DS0FilterTable,
        ///      &quot;Sum_of_Cost_of_Goods_Sold_FYTD&quot;, &apos;Measure&apos;[Sum of Cost of Goods Sold FYTD]
        ///    ),
        ///    &apos;Date&apos;[Financial Year (Calendar)],
        ///    1
        ///  )
        ///
        ///ORDER BY
        ///  &apos;Date&apos;[Financial Year (Calendar)]
        ///.
        /// </summary>
        internal static string TestResource_ActualQuery_30ba6fe4ea854003adc65b4ae5e9619d
        {
            get
            {
                return ResourceManager.GetString("TestResource_ActualQuery_30ba6fe4ea854003adc65b4ae5e9619d", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // DAX Query
        ///DEFINE VAR __DS0FilterTable = 
        ///  TREATAS({&quot;2019-2020&quot;}, &apos;Date&apos;[Financial Year (Calendar)])
        ///
        ///EVALUATE
        ///  TOPN(
        ///    501,
        ///    SUMMARIZECOLUMNS(
        ///      &apos;Date&apos;[Financial Year (Calendar)],
        ///      __DS0FilterTable,
        ///      &quot;Sum_of_Cost_of_Goods_Sold_PM_FYTD&quot;, &apos;Measure&apos;[Sum of Cost of Goods Sold PM FYTD]
        ///    ),
        ///    &apos;Date&apos;[Financial Year (Calendar)],
        ///    1
        ///  )
        ///
        ///ORDER BY
        ///  &apos;Date&apos;[Financial Year (Calendar)]
        ///.
        /// </summary>
        internal static string TestResource_ActualQuery_c672e003103f429184b777e5b3cdffa4
        {
            get
            {
                return ResourceManager.GetString("TestResource_ActualQuery_c672e003103f429184b777e5b3cdffa4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Byte[].
        /// </summary>
        internal static byte[] TestResource_ComparisonManifest_46b30c8c77854d3e9e84439cf2c6d938
        {
            get
            {
                object obj = ResourceManager.GetObject("TestResource_ComparisonManifest_46b30c8c77854d3e9e84439cf2c6d938", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Byte[].
        /// </summary>
        internal static byte[] TestResource_ComparisonManifest_c36f1d8cbbff4b289c58ce67f477b52e
        {
            get
            {
                object obj = ResourceManager.GetObject("TestResource_ComparisonManifest_c36f1d8cbbff4b289c58ce67f477b52e", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Byte[].
        /// </summary>
        internal static byte[] TestResource_DWHstage_9c0a93a6e32045e78e7d50bba97c5f8f
        {
            get
            {
                object obj = ResourceManager.GetObject("TestResource_DWHstage_9c0a93a6e32045e78e7d50bba97c5f8f", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with cte  as
        ///(
        ///select ga.ACCOUNT_TYPE,
        ///iif(ga.ACCOUNT_TYPE = &apos;E&apos;,sum( CAST(DecryptByCert(Cert_Id(&apos;Fincertificate&apos;), AMOUNT, N&apos;75ugBRGy&apos;) AS money) *-1),
        ///sum( CAST(DecryptByCert(Cert_Id(&apos;Fincertificate&apos;), AMOUNT, N&apos;75ugBRGy&apos;) AS money)) ) AS Sum_of_CostofGoodSold
        ///        FROM [Dwh].[dw].[factGeneralLedgerJournal] fj
        ///        inner join dw.dimGeneralLedgerAccount  ga on fj.DIM_GENERAL_LEDGER_ACCOUNT_KEY=ga.DIM_GENERAL_LEDGER_ACCOUNT_KEY
        ///    where
        ///        (
        ///            ga.ACCOUNT_NUMBER  in 
        ///			(&apos;1000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestResource_ExpectedQuery_27860fdfe98a4c9089800d9e987d1a72
        {
            get
            {
                return ResourceManager.GetString("TestResource_ExpectedQuery_27860fdfe98a4c9089800d9e987d1a72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with cte  as
        ///(
        ///select ga.ACCOUNT_TYPE,
        ///iif(ga.ACCOUNT_TYPE = &apos;E&apos;,sum( CAST(DecryptByCert(Cert_Id(&apos;Fincertificate&apos;), AMOUNT, N&apos;75ugBRGy&apos;) AS money) *-1),
        ///sum( CAST(DecryptByCert(Cert_Id(&apos;Fincertificate&apos;), AMOUNT, N&apos;75ugBRGy&apos;) AS money)) ) AS Sum_of_CostofGoodSold
        ///        FROM [Dwh].[dw].[factGeneralLedgerJournal] fj
        ///        inner join dw.dimGeneralLedgerAccount  ga on fj.DIM_GENERAL_LEDGER_ACCOUNT_KEY=ga.DIM_GENERAL_LEDGER_ACCOUNT_KEY
        ///    where
        ///        (
        ///            ga.ACCOUNT_NUMBER  IN 
        ///			(&apos;1000 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestResource_ExpectedQuery_8629fb71ec16453f92789ff33904fd31
        {
            get
            {
                return ResourceManager.GetString("TestResource_ExpectedQuery_8629fb71ec16453f92789ff33904fd31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Byte[].
        /// </summary>
        internal static byte[] TestResource_SSASMatrixProduction_b89de6cae6604205b75e0566246db3fc
        {
            get
            {
                object obj = ResourceManager.GetObject("TestResource_SSASMatrixProduction_b89de6cae6604205b75e0566246db3fc", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}

