// <auto-generated />
namespace DWH_Automation_Testing.DanElzerAverageCommission_Output
{
    using global::System;
    using global::System.Diagnostics.CodeAnalysis;
    using global::System.Resources;
    using global::System.Globalization;
    using global::System.ComponentModel;
    using global::System.CodeDom.Compiler;
    using global::System.Diagnostics;
    using global::System.Runtime.CompilerServices;
    using System.Collections.Generic;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [DebuggerNonUserCode]
    [CompilerGenerated]
    internal class Resources
    {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources()
        {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    ResourceManager temp = new ResourceManager("DWH_Automation_Testing.DanElzerAverageCommission_Output.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-16&quot;?&gt;&lt;TestManifest failOnServerPublishFailureExpression=&quot;False&quot; testSuiteId=&quot;ae79b540-c994-4d59-9294-b3d13bfa03a9&quot; testSuiteName=&quot;Dan Elzer Average Commission&quot; testGroupId=&quot;7594a693-f950-4302-a702-37eb1620d869&quot; testGroupName=&quot;Dan Elzer Average Commission&quot; isSingleGroupMode=&quot;True&quot; publishUrl=&quot;https://test-api.sentryone.com&quot; publishUserName=&quot;asingh@barfoot.co.nz&quot; publishorganizationIdentifier=&quot;346&quot; accessToken=&quot;OcjV3EfxP3aWHJten0vq8y1hlAFEIPCqVPq0m7FDq5aQWcKm0kaYv/Nwmewb18la0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestManifest_DanElzerAverageCommission_7594a693f9504302a70237eb1620d869
        {
            get
            {
                return ResourceManager.GetString("TestManifest_DanElzerAverageCommission_7594a693f9504302a70237eb1620d869", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // DAX Query
        ///DEFINE VAR __DS0FilterTable = 
        ///  TREATAS({&quot;2019-2020&quot;}, &apos;Date&apos;[Financial Year (Calendar)])
        ///
        ///EVALUATE
        ///  TOPN(
        ///    501,
        ///    SUMMARIZECOLUMNS(
        ///      &apos;Date&apos;[Financial Year (Calendar)],
        ///      __DS0FilterTable,
        ///      &quot;Average_GCI_Per_Listing_FYTD_Live_&quot;, &apos;Measure&apos;[Average GCI Per Listing FYTD(Live)]
        ///    ),
        ///    [Average_GCI_Per_Listing_FYTD_Live_],
        ///    0,
        ///    &apos;Date&apos;[Financial Year (Calendar)],
        ///    1
        ///  )
        ///
        ///ORDER BY
        ///  [Average_GCI_Per_Listing_FYTD_Live_] DESC, &apos;Date&apos;[Financial Year (Ca [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestResource_ActualQuery_192dc5b8a6e746959717be64305f205c
        {
            get
            {
                return ResourceManager.GetString("TestResource_ActualQuery_192dc5b8a6e746959717be64305f205c", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // DAX Query
        ///DEFINE VAR __DS0FilterTable = 
        ///  TREATAS({TRUE}, &apos;Date&apos;[Is Last Financial Year])
        ///
        ///EVALUATE
        ///  TOPN(
        ///    501,
        ///    SUMMARIZECOLUMNS(
        ///      &apos;Date&apos;[Is Last Financial Year],
        ///      __DS0FilterTable,
        ///      &quot;Count_of_Listing_Productivity_FYTD_Live_&quot;, &apos;Measure&apos;[Count of Listing Productivity FYTD(Live)]
        ///    ),
        ///    [Count_of_Listing_Productivity_FYTD_Live_],
        ///    0,
        ///    &apos;Date&apos;[Is Last Financial Year],
        ///    1
        ///  )
        ///
        ///ORDER BY
        ///  [Count_of_Listing_Productivity_FYTD_Live_] DESC, &apos;Date&apos;[Is Last Fi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestResource_ActualQuery_1e196568d1b04ed992d600a17ad1420b
        {
            get
            {
                return ResourceManager.GetString("TestResource_ActualQuery_1e196568d1b04ed992d600a17ad1420b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // DAX Query
        ///EVALUATE
        ///  ROW(
        ///    &quot;SumFull_Selling_Commission&quot;, CALCULATE(SUM(&apos;Listing&apos;[Full Selling Commission]))
        ///  ).
        /// </summary>
        internal static string TestResource_ActualQuery_2796ba3f1836410ca57c47fa83eafe42
        {
            get
            {
                return ResourceManager.GetString("TestResource_ActualQuery_2796ba3f1836410ca57c47fa83eafe42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // DAX Query
        ///DEFINE
        ///  VAR __DS0FilterTable = 
        ///    TREATAS({&quot;January&quot;}, &apos;Date&apos;[Calendar Month Name])
        ///
        ///  VAR __DS0FilterTable2 = 
        ///    FILTER(KEEPFILTERS(VALUES(&apos;Date&apos;[Calendar Year])), &apos;Date&apos;[Calendar Year] = 2020)
        ///
        ///EVALUATE
        ///  TOPN(
        ///    501,
        ///    SUMMARIZECOLUMNS(
        ///      &apos;Date&apos;[Calendar Month Name],
        ///      &apos;Date&apos;[Financial Month Number],
        ///      &apos;Date&apos;[Calendar Year],
        ///      __DS0FilterTable,
        ///      __DS0FilterTable2,
        ///      &quot;Count_of_Selling_Productivity_Rolling_12_Months_Live_&quot;, ROUNDDOWN((&apos;Measure [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestResource_ActualQuery_72223513875f49d0bfef70a454e7ca42
        {
            get
            {
                return ResourceManager.GetString("TestResource_ActualQuery_72223513875f49d0bfef70a454e7ca42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // DAX Query
        ///DEFINE
        ///  VAR __DS0FilterTable = 
        ///    TREATAS({&quot;January&quot;}, &apos;Date&apos;[Calendar Month Name])
        ///
        ///  VAR __DS0FilterTable2 = 
        ///    FILTER(KEEPFILTERS(VALUES(&apos;Date&apos;[Calendar Year])), &apos;Date&apos;[Calendar Year] = 2020)
        ///
        ///EVALUATE
        ///  TOPN(
        ///    501,
        ///    SUMMARIZECOLUMNS(
        ///      &apos;Date&apos;[Calendar Month Name],
        ///      &apos;Date&apos;[Financial Month Number],
        ///      &apos;Date&apos;[Calendar Year],
        ///      __DS0FilterTable,
        ///      __DS0FilterTable2,
        ///      &quot;Average_GCI_Per_Sale_Rolling_12_Months_Live_&quot;, &apos;Measure&apos;[Average GCI Per Sa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestResource_ActualQuery_82c3046a199d407a87f0c977bbb7f6ef
        {
            get
            {
                return ResourceManager.GetString("TestResource_ActualQuery_82c3046a199d407a87f0c977bbb7f6ef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // DAX Query
        ///DEFINE VAR __DS0FilterTable = 
        ///  TREATAS({&quot;2019-2020&quot;}, &apos;Date&apos;[Financial Year (Calendar)])
        ///
        ///EVALUATE
        ///  TOPN(
        ///    501,
        ///    SUMMARIZECOLUMNS(
        ///      &apos;Date&apos;[Financial Year (Calendar)],
        ///      __DS0FilterTable,
        ///      &quot;Average_GCI_Per_Sale_FYTD_Live_&quot;, &apos;Measure&apos;[Average GCI Per Sale FYTD(Live)]
        ///    ),
        ///    [Average_GCI_Per_Sale_FYTD_Live_],
        ///    0,
        ///    &apos;Date&apos;[Financial Year (Calendar)],
        ///    1
        ///  )
        ///
        ///ORDER BY
        ///  [Average_GCI_Per_Sale_FYTD_Live_] DESC, &apos;Date&apos;[Financial Year (Calendar)]
        ///.
        /// </summary>
        internal static string TestResource_ActualQuery_9c9596b69663454cae718c20f5be4e4f
        {
            get
            {
                return ResourceManager.GetString("TestResource_ActualQuery_9c9596b69663454cae718c20f5be4e4f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // DAX Query
        ///DEFINE
        ///  VAR __DS0FilterTable = 
        ///    TREATAS({&quot;January&quot;}, &apos;Date&apos;[Calendar Month Name])
        ///
        ///  VAR __DS0FilterTable2 = 
        ///    FILTER(KEEPFILTERS(VALUES(&apos;Date&apos;[Calendar Year])), &apos;Date&apos;[Calendar Year] = 2020)
        ///
        ///EVALUATE
        ///  TOPN(
        ///    501,
        ///    SUMMARIZECOLUMNS(
        ///      &apos;Date&apos;[Calendar Month Name],
        ///      &apos;Date&apos;[Financial Month Number],
        ///      &apos;Date&apos;[Calendar Year],
        ///      __DS0FilterTable,
        ///      __DS0FilterTable2,
        ///      &quot;Count_of_Listing_Productivity_Rolling_12_Months_Live_&quot;, ROUNDDOWN((&apos;Measure [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestResource_ActualQuery_d7b527bab3314421af75ec2592f60a05
        {
            get
            {
                return ResourceManager.GetString("TestResource_ActualQuery_d7b527bab3314421af75ec2592f60a05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // DAX Query
        ///DEFINE
        ///  VAR __DS0FilterTable = 
        ///    TREATAS({&quot;January&quot;}, &apos;Date&apos;[Calendar Month Name])
        ///
        ///  VAR __DS0FilterTable2 = 
        ///    FILTER(KEEPFILTERS(VALUES(&apos;Date&apos;[Calendar Year])), &apos;Date&apos;[Calendar Year] = 2020)
        ///
        ///EVALUATE
        ///  TOPN(
        ///    501,
        ///    SUMMARIZECOLUMNS(
        ///      &apos;Date&apos;[Calendar Month Name],
        ///      &apos;Date&apos;[Financial Month Number],
        ///      &apos;Date&apos;[Calendar Year],
        ///      __DS0FilterTable,
        ///      __DS0FilterTable2,
        ///      &quot;Average_GCI_Per_Listing_Rolling_12_Months_Live_&quot;, &apos;Measure&apos;[Average GCI Per [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestResource_ActualQuery_d921d9307a144810ba9f40a678fa598f
        {
            get
            {
                return ResourceManager.GetString("TestResource_ActualQuery_d921d9307a144810ba9f40a678fa598f", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // DAX Query
        ///DEFINE VAR __DS0FilterTable = 
        ///  TREATAS({TRUE}, &apos;Date&apos;[Is Last Financial Year])
        ///
        ///EVALUATE
        ///  TOPN(
        ///    501,
        ///    SUMMARIZECOLUMNS(
        ///      &apos;Date&apos;[Is Last Financial Year],
        ///      __DS0FilterTable,
        ///      &quot;Count_of_Selling_Productivity_FYTD_Live_&quot;, &apos;Measure&apos;[Count of Selling Productivity FYTD(Live)]
        ///    ),
        ///    [Count_of_Selling_Productivity_FYTD_Live_],
        ///    0,
        ///    &apos;Date&apos;[Is Last Financial Year],
        ///    1
        ///  )
        ///
        ///ORDER BY
        ///  [Count_of_Selling_Productivity_FYTD_Live_] DESC, &apos;Date&apos;[Is Last Fi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestResource_ActualQuery_e52e3b39fcc040c5bb0b3c13312eaa5e
        {
            get
            {
                return ResourceManager.GetString("TestResource_ActualQuery_e52e3b39fcc040c5bb0b3c13312eaa5e", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Byte[].
        /// </summary>
        internal static byte[] TestResource_ComparisonManifest_056ed04c389c4f8b9fd58b8e3e92c800
        {
            get
            {
                object obj = ResourceManager.GetObject("TestResource_ComparisonManifest_056ed04c389c4f8b9fd58b8e3e92c800", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Byte[].
        /// </summary>
        internal static byte[] TestResource_ComparisonManifest_16375175e0704444bc42b97d2a95228b
        {
            get
            {
                object obj = ResourceManager.GetObject("TestResource_ComparisonManifest_16375175e0704444bc42b97d2a95228b", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Byte[].
        /// </summary>
        internal static byte[] TestResource_ComparisonManifest_658f5d64b636403babd6e0c1b8041ad0
        {
            get
            {
                object obj = ResourceManager.GetObject("TestResource_ComparisonManifest_658f5d64b636403babd6e0c1b8041ad0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Byte[].
        /// </summary>
        internal static byte[] TestResource_ComparisonManifest_77dd3d48b11245fe897ae70f09d86d6b
        {
            get
            {
                object obj = ResourceManager.GetObject("TestResource_ComparisonManifest_77dd3d48b11245fe897ae70f09d86d6b", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Byte[].
        /// </summary>
        internal static byte[] TestResource_ComparisonManifest_91f4837032ba4b4b9475229f327b46c0
        {
            get
            {
                object obj = ResourceManager.GetObject("TestResource_ComparisonManifest_91f4837032ba4b4b9475229f327b46c0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Byte[].
        /// </summary>
        internal static byte[] TestResource_ComparisonManifest_95b112e5b16b4ec9829d93b3d2518284
        {
            get
            {
                object obj = ResourceManager.GetObject("TestResource_ComparisonManifest_95b112e5b16b4ec9829d93b3d2518284", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Byte[].
        /// </summary>
        internal static byte[] TestResource_ComparisonManifest_be7d93a28cce477881f2e3f4bc7a20fc
        {
            get
            {
                object obj = ResourceManager.GetObject("TestResource_ComparisonManifest_be7d93a28cce477881f2e3f4bc7a20fc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Byte[].
        /// </summary>
        internal static byte[] TestResource_ComparisonManifest_f099195aabad43dead7e1987aa6d0800
        {
            get
            {
                object obj = ResourceManager.GetObject("TestResource_ComparisonManifest_f099195aabad43dead7e1987aa6d0800", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Byte[].
        /// </summary>
        internal static byte[] TestResource_ComparisonManifest_f5e9a24dc9444775a5975d837a1755cd
        {
            get
            {
                object obj = ResourceManager.GetObject("TestResource_ComparisonManifest_f5e9a24dc9444775a5975d837a1755cd", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Byte[].
        /// </summary>
        internal static byte[] TestResource_DWHProd_c2a749ae94fd4b38a26c8ca0efb4360b
        {
            get
            {
                object obj = ResourceManager.GetObject("TestResource_DWHProd_c2a749ae94fd4b38a26c8ca0efb4360b", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Byte[].
        /// </summary>
        internal static byte[] TestResource_DWHstage_9c0a93a6e32045e78e7d50bba97c5f8f
        {
            get
            {
                object obj = ResourceManager.GetObject("TestResource_DWHstage_9c0a93a6e32045e78e7d50bba97c5f8f", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with ctet1 as (
        ///Select sum (fs.[Net Commission]) SellingComm ,fs.[Listing Number],s.DIM_SALES_KEY from viewFactCommission fs
        ///join dw.dimSales s
        ///on fs.DIM_SALES_KEY=s.DIM_SALES_KEY
        ///where s.IS_SALECLEARED=1
        ///and fs.[Commission Type]=&apos;Selling Commission&apos;
        ///and fs.DIM_DATE_KEY between &apos;20190401&apos; and &apos;20200331&apos;
        ///--and [Listing Number]=&apos;787230&apos;
        ///group by fs.[Listing Number] ,s.DIM_SALES_KEY
        ///),
        ///ctet2 as
        ///(
        ///Select sum (fs.[Net Commission]) fulllisting,l.LISTING_NUMBER
        ///from viewFactCommission fs
        ///join dw.dimS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestResource_ExpectedQuery_370f112048ca42b7a27068d01e671397
        {
            get
            {
                return ResourceManager.GetString("TestResource_ExpectedQuery_370f112048ca42b7a27068d01e671397", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with ctet1 as (
        ///Select SUM (fs.[Net Commission]) ListingComm ,fs.[Listing Number],s.DIM_SALES_KEY from viewFactCommission fs
        ///join dw.dimSales s
        ///on fs.DIM_SALES_KEY=s.DIM_SALES_KEY
        ///where s.IS_SALECLEARED=1
        ///and fs.[Commission Type]=&apos;Listing Commission&apos;
        ///and fs.DIM_DATE_KEY between &apos;20190201&apos; and &apos;20200131&apos;
        ///--and [Listing Number]=&apos;787230&apos;
        ///group by fs.[Listing Number] ,s.DIM_SALES_KEY
        ///),
        ///ctet2 as
        ///(
        ///Select sum (fs.[Net Commission]) fulllisting,l.LISTING_NUMBER
        ///from viewFactCommission fs
        ///join dw.dimS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestResource_ExpectedQuery_645d53a44f7243999570b24c2cdb94e3
        {
            get
            {
                return ResourceManager.GetString("TestResource_ExpectedQuery_645d53a44f7243999570b24c2cdb94e3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with ctet1 as (
        ///Select SUM (fs.[Net Commission]) ListingComm ,fs.[Listing Number],s.DIM_SALES_KEY from viewFactCommission fs
        ///join dw.dimSales s
        ///on fs.DIM_SALES_KEY=s.DIM_SALES_KEY
        ///where s.IS_SALECLEARED=1
        ///and fs.[Commission Type]=&apos;Listing Commission&apos;
        ///and fs.DIM_DATE_KEY between &apos;20190401&apos; and &apos;20200331&apos;
        ///--and [Listing Number]=&apos;787230&apos;
        ///group by fs.[Listing Number] ,s.DIM_SALES_KEY
        ///),
        ///ctet2 as
        ///(
        ///Select sum (fs.[Net Commission]) fulllisting,l.LISTING_NUMBER
        ///from viewFactCommission fs
        ///join dw.dimS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestResource_ExpectedQuery_66c122f6655b4b8d92134efc5eba46ec
        {
            get
            {
                return ResourceManager.GetString("TestResource_ExpectedQuery_66c122f6655b4b8d92134efc5eba46ec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with ctet1 as (
        ///Select sum (fs.[Net Commission]) SellingComm,fs.[Listing Number],s.DIM_SALES_KEY from viewFactCommission fs
        ///join dw.dimSales s
        ///on fs.DIM_SALES_KEY=s.DIM_SALES_KEY
        ///where s.IS_SALECLEARED=1
        ///and fs.[Commission Type]=&apos;Selling Commission&apos;
        ///and fs.DIM_DATE_KEY between &apos;20190201&apos; and &apos;20200131&apos;
        ///--and [Listing Number]=&apos;787230&apos;
        ///group by fs.[Listing Number] ,s.DIM_SALES_KEY
        ///),
        ///
        ///ctet2 as
        ///(
        ///Select sum (fs.[Net Commission]) fulllisting,fs.[Listing Number] 
        ///from viewFactCommission fs
        ///join dw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestResource_ExpectedQuery_9db5984e727d419791885d85f897f727
        {
            get
            {
                return ResourceManager.GetString("TestResource_ExpectedQuery_9db5984e727d419791885d85f897f727", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with ctet1 as (
        ///Select sum (fs.[Net Commission]) SellingComm ,fs.[Listing Number],s.DIM_SALES_KEY from viewFactCommission fs
        ///join dw.dimSales s
        ///on fs.DIM_SALES_KEY=s.DIM_SALES_KEY
        ///where s.IS_SALECLEARED=1
        ///and fs.[Commission Type]=&apos;Selling Commission&apos;
        ///and fs.DIM_DATE_KEY between &apos;20190201&apos; and &apos;20200131&apos;
        ///--and [Listing Number]=&apos;787230&apos;
        ///group by fs.[Listing Number] ,s.DIM_SALES_KEY
        ///),
        ///ctet2 as
        ///(
        ///Select sum (fs.[Net Commission]) fulllisting,l.LISTING_NUMBER
        ///from viewFactCommission fs
        ///join dw.dimS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestResource_ExpectedQuery_c150efec05c94a3ba864948353e9f0ff
        {
            get
            {
                return ResourceManager.GetString("TestResource_ExpectedQuery_c150efec05c94a3ba864948353e9f0ff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select SUM (fs.[Net Commission]) SumFull_Selling_Commission from viewFactCommission fs
        ///join dw.dimSales s 
        ///on fs.DIM_SALES_KEY=s.DIM_SALES_KEY
        ///join dw.dimListing l
        ///on l.DIM_LISTING_KEY=fs.DIM_LISTING_KEY
        ///where s.IS_SALECLEARED=1
        ///and fs.[Commission Type]=&apos;Selling Commission&apos;.
        /// </summary>
        internal static string TestResource_ExpectedQuery_d8bd41baa60e4c23a12d7d18832e3b21
        {
            get
            {
                return ResourceManager.GetString("TestResource_ExpectedQuery_d8bd41baa60e4c23a12d7d18832e3b21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with ctet1 as (
        ///Select sum (fs.[Net Commission]) SellingComm,fs.[Listing Number],s.DIM_SALES_KEY from viewFactCommission fs
        ///join dw.dimSales s
        ///on fs.DIM_SALES_KEY=s.DIM_SALES_KEY
        ///where s.IS_SALECLEARED=1
        ///and fs.[Commission Type]=&apos;Selling Commission&apos;
        ///and fs.DIM_DATE_KEY between &apos;20190401&apos; and &apos;20200331&apos;
        ///--and [Listing Number]=&apos;787230&apos;
        ///group by fs.[Listing Number] ,s.DIM_SALES_KEY
        ///),
        ///
        ///ctet2 as
        ///(
        ///Select sum (fs.[Net Commission]) fulllisting,fs.[Listing Number] 
        ///from viewFactCommission fs
        ///join dw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestResource_ExpectedQuery_df9b9f58657a4c66b9c964b8fbe176f9
        {
            get
            {
                return ResourceManager.GetString("TestResource_ExpectedQuery_df9b9f58657a4c66b9c964b8fbe176f9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with ctet1 as (
        ///Select SUM (fs.[Net Commission]) ListingComm,fs.[Listing Number],s.DIM_SALES_KEY from viewFactCommission fs
        ///join dw.dimSales s
        ///on fs.DIM_SALES_KEY=s.DIM_SALES_KEY
        ///where s.IS_SALECLEARED=1
        ///and fs.[Commission Type]=&apos;Listing Commission&apos;
        ///and fs.DIM_DATE_KEY between &apos;20190201&apos; and &apos;20200131&apos;
        ///--and [Listing Number]=&apos;787230&apos;
        ///group by fs.[Listing Number] ,s.DIM_SALES_KEY
        ///),
        ///
        ///ctet2 as
        ///(
        ///Select sum (fs.[Net Commission]) fulllisting,fs.[Listing Number] 
        ///from viewFactCommission fs
        ///join dw [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestResource_ExpectedQuery_e34ac9975d1242ce9363bb6a21edc0f9
        {
            get
            {
                return ResourceManager.GetString("TestResource_ExpectedQuery_e34ac9975d1242ce9363bb6a21edc0f9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with ctet1 as (
        ///Select SUM (fs.[Net Commission]) ListingComm ,fs.[Listing Number],s.DIM_SALES_KEY from viewFactCommission fs
        ///join dw.dimSales s
        ///on fs.DIM_SALES_KEY=s.DIM_SALES_KEY
        ///where s.IS_SALECLEARED=1
        ///and fs.[Commission Type]=&apos;Listing Commission&apos;
        ///and fs.DIM_DATE_KEY between &apos;20190401&apos; and &apos;20200331&apos;
        ///--and [Listing Number]=&apos;787230&apos;
        ///group by fs.[Listing Number] ,s.DIM_SALES_KEY
        ///),
        ///
        ///ctet2 as
        ///(
        ///Select sum (fs.[Net Commission]) fulllisting,fs.[Listing Number] 
        ///from viewFactCommission fs
        ///join d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TestResource_ExpectedQuery_ef80608174314156933f6517b9484ed7
        {
            get
            {
                return ResourceManager.GetString("TestResource_ExpectedQuery_ef80608174314156933f6517b9484ed7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Byte[].
        /// </summary>
        internal static byte[] TestResource_SSASMatrixProduction_b89de6cae6604205b75e0566246db3fc
        {
            get
            {
                object obj = ResourceManager.GetObject("TestResource_SSASMatrixProduction_b89de6cae6604205b75e0566246db3fc", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type Byte[].
        /// </summary>
        internal static byte[] TestResource_SSASMatrixStage_8e44e5c05a37464488a9d311993a301b
        {
            get
            {
                object obj = ResourceManager.GetObject("TestResource_SSASMatrixStage_8e44e5c05a37464488a9d311993a301b", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}

